name: Build Deps (Ubuntu)

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to build'
        required: true
        default: 'libreoffice-24-8'
      release_tag:
        description: 'Existing Release tag to upload to'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Check if Release tag exists
      uses: mukunku/tag-exists-action@v1.6.0
      id: check-tag
      with: 
        tag: 'v24.8.x'

    - name: Release tag not exists
      run: echo "Tag does not exist, exiting..." && exit 1
      if: steps.check-tag.outputs.exists != 'true'

    - name: Check out code
      uses: actions/checkout@v4

    - name: Clone Libreoffice
      run: |
        git clone --depth=1 --branch ${{ github.event.inputs.branch }} https://github.com/LibreOffice/core.git

    - name: Get latest commit ID
      id: get_commit_id
      run: |
        cd core
        echo "commit_id=$(git rev-parse HEAD | cut -c1-7)" >> $GITHUB_ENV

    - name: Cache tarballs
      id: cache_tarballs
      uses: actions/cache@v4
      with:
        path: core/external/tarballs
        key: tarballs-${{ hashFiles('core/download.lst') }}
        restore-keys: |
          tarballs-
        enableCrossOsArchive: true

    - name: Pull Docker image
      run: |
        docker pull ghcr.io/zerolover/github-action/lo:dev

    - name: Compile
      run: |
        docker run --rm \
          -v ${{ github.workspace }}:/workspace \
          -w /workspace \
          ghcr.io/zerolover/github-action/lo:dev \
          /bin/bash /workspace/script/build-deps-ubuntu.sh

    - name: Compress the output
      run: |
        tar -I "xz -T0" -cf deps_ubuntu_${{ github.event.inputs.branch }}_${{ env.commit_id }}.tar.xz deps/

    - name: Upload build artifacts to Existing Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.event.inputs.release_tag }}
        files: deps_ubuntu_${{ github.event.inputs.branch }}_${{ env.commit_id }}.tar.xz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
