name: Build Deps (Ubuntu)

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to build'
        required: true
        default: 'master'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Clone Libreoffice
      run: |
        git clone --depth=1 --branch ${{ github.event.inputs.branch }} https://github.com/LibreOffice/core.git

    - name: Get latest commit ID
      id: get_commit_id
      run: |
        cd core
        echo "commit_id=$(git rev-parse HEAD | cut -c1-7)" >> $GITHUB_ENV

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Pull Docker image
      run: |
        docker pull ghcr.io/zerolover/github-action/lo:v0.1

    - name: Compile
      run: |
        docker run --rm \
          -v ${{ github.workspace }}:/workspace \
          -w /workspace \
          ghcr.io/zerolover/github-action/lo:v0.1 \
          /bin/bash /workspace/script/build-deps-ubuntu.sh

    - name: List dolphin directory contents
      run: ls -la dolphin

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dolphin-${{ github.event.inputs.branch }}-${{ env.commit_id }}
        path: dolphin
