name: test s3

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2019
    permissions:
      contents: write

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    # - name: test
    #   run: |
    #     C:\msys64\usr\bin\pacman.exe -S --noconfirm bison flex gperf libxslt
    #     C:\msys64\usr\bin\bison.exe --version
    #     C:\msys64\usr\bin\gperf.exe --version
    #     C:\msys64\usr\bin\xsltproc.exe --version

    - name: Cache Cygwin
      uses: actions/cache@v4
      with:
        path: D:\cygwin
        key: cygwin-windows-2019
        fail-on-cache-miss: true

    - name: List installed packages
      run: |
        basic() {
          pkg-config --cflags --libs python3
          ls -alht /usr/lib/x86_64-linux-gnu/libpy*
        }
        basic
      shell: D:\cygwin\bin\bash.exe --login --norc -eo pipefail -o igncr '{0}'

    - uses: ynab/system-info-action@v1.3
      id: system-info
    - name: debug
      run: |
        echo "System Info:"
        echo "CPU Core: ${{ steps.system-info.outputs.cpu-core }}"
        echo "CPU Model: ${{ steps.system-info.outputs.cpu-model }}"
        echo "Hostname: ${{ steps.system-info.outputs.hostname }}"
        echo "Kernel Release: ${{ steps.system-info.outputs.kernel-release }}"
        echo "Kernel Version: ${{ steps.system-info.outputs.kernel-version }}"
        echo "Name: ${{ steps.system-info.outputs.name }}"
        echo "Platform: ${{ steps.system-info.outputs.platform }}"
        echo "Release: ${{ steps.system-info.outputs.release }}"
        echo "Total Memory: ${{ steps.system-info.outputs.totalmem }}"