name: test s3

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14
    permissions:
      contents: write

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: test
      run: |
        pwd
        gtar -I "zstd -T0 -6 -k" -cf docker.tzst docker

    - uses: ynab/system-info-action@v1.3
      id: system-info
    - name: debug
      run: |
        echo "System Info:"
        echo "CPU Core: ${{ steps.system-info.outputs.cpu-core }}"
        echo "CPU Model: ${{ steps.system-info.outputs.cpu-model }}"
        echo "Hostname: ${{ steps.system-info.outputs.hostname }}"
        echo "Kernel Release: ${{ steps.system-info.outputs.kernel-release }}"
        echo "Kernel Version: ${{ steps.system-info.outputs.kernel-version }}"
        echo "Name: ${{ steps.system-info.outputs.name }}"
        echo "Platform: ${{ steps.system-info.outputs.platform }}"
        echo "Release: ${{ steps.system-info.outputs.release }}"
        echo "Total Memory: ${{ steps.system-info.outputs.totalmem }}"